default_platform(:ios)

platform :ios do
  before_all do
    setup_ci if ENV["CI"]
    connect_api_key
  end

  private_lane :connect_api_key do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_API_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_filepath: ENV.fetch("APPSTORE_API_KEY_PATH"),
      duration: 1200,
      in_house: false
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    team_id = ENV.fetch("DEVELOPMENT_TEAM")

    increment_build_number(
      xcodeproj: "BasicApp.xcodeproj",
      build_number: ENV.fetch("BUILD_NUMBER", "1")
    )

    cert(
      team_id: team_id,
      development: false
    )

    sigh(
      team_id: team_id,
      app_identifier: "com.brunabaudel.BasicApp"
    )

    build_app(
      project: "BasicApp.xcodeproj",
      scheme: "BasicApp",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "BasicApp.ipa"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )
  end
end
